version: '3'
services:
  # 主库
  mysql-master:
    image: mysql:8.0.26 # MySQL 版本
    restart: always
    ports:
      - "3307:3306"
    container_name: mysql-master
    network_mode: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - 'mysql-master:/etc/mysql'
      - '/var/mysql-master/logs:/var/log/mysql'
      - '/var/mysql-master/data:/var/lib/mysql'
    command:
      - "--lower_case_table_names=1"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
      - "--default-authentication-plugin=mysql_native_password"

  # 从库0
  mysql-slaver0:
    image: mysql:8.0.26
    restart: always
    ports:
      - "3308:3306"
    container_name: mysql-slaver0
    network_mode: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - 'mysql-slaver0:/etc/mysql'
      - '/var/mysql-slaver0/logs:/var/log/mysql'
      - '/var/mysql-slaver0/data:/var/lib/mysql'
    command:
      - "--lower_case_table_names=1"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
      - "--default-authentication-plugin=mysql_native_password"

  # 从库1
  mysql-slaver1:
    image: mysql:8.0.26
    restart: always
    ports:
      - "3309:3306"
    container_name: mysql-slaver1
    network_mode: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - 'mysql-slaver1:/etc/mysql'
      - '/var/mysql-slaver1/logs:/var/log/mysql'
      - '/var/mysql-slaver1/data:/var/lib/mysql'
    command:
      - "--lower_case_table_names=1"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
      - "--default-authentication-plugin=mysql_native_password"

volumes:
  mysql-master:
  mysql-slaver0:
  mysql-slaver1:

networks:
  mysql: